server:
  servlet:
    context-path: /api

spring:
  application:
    name: rate-limit-service
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60m

bucket4j:
  enabled: true
  cache-to-use: jcache
  methods:
    - name: api-external
      cache-name: rate-limit-buckets
      rate-limit:
        bandwidths:
          - capacity: 2
            time: 1
            unit: minutes
            refill-speed: interval
    - name: api-internal
      cache-name: rate-limit-buckets
      rate-limit:
        bandwidths:
          - capacity: 2
            time: 1
            unit: minutes
            refill-speed: interval


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always