spring:
  application:
    name: poc-jpa-orm-spring-boot

  flyway:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3310/poc_jpa_db?useSSL=false
    username: app_user
    password: app_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # Connection pool settings
      pool-name: HikariCP-POC
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always