spring:
  application:
    name: poc-jpa-orm-spring-boot
  
  datasource:
    url: jdbc:mysql://localhost:3310/poc_jpa_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: app_user
    password: app_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # Connection pool settings
      pool-name: HikariCP-POC
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      
      # Connection test settings
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4
      
      # Performance settings
      auto-commit: true
      read-only: false
      
      # Database specific settings
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
        type:
          descriptor:
            sql: trace
        jdbc:
          batch_size: 20
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 2048
          plan_parameter_metadata_max_size: 128
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
    defer-datasource-initialization: true
  
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

# Actuator configuration for monitoring HikariCP
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
  metrics:
    enable:
      hikari: true

# Logging configuration to show SQL with parameter values
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE
        stat: DEBUG
      springframework:
        transaction: DEBUG
    com:
      zaxxer:
        hikari: DEBUG
    th:
      eknarong:
        aph:
          poc:
            pocjpaormspringboot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
