version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: poc-jpa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poc_jpa_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3310:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password